### ISSUE TITLE
Loading a Chart

### ISSUE THREAD

**Issue by BruunoSCP** [accountrev/funkychart#4]
So, I did everything but when I'm trying to load the chart it says "Load a song" even if I already loaded it, the chart doesn't work (I used the examples charts and audios too btw with krnl). It doesn't say that the "???.lua" does not exist, it doesn't load when I click in Play Chart, here some screenshots.
![adada](https://user-images.githubusercontent.com/103290917/162543112-f6449ef0-cf45-4b8c-84ff-719200853da2.png)
![image](https://user-images.githubusercontent.com/103290917/162543136-2b3ea9a1-8c8f-4834-95d4-5feb4c44e084.png)
![image](https://user-images.githubusercontent.com/103290917/162543163-fd1d41e4-7593-47cb-b284-de8fa06b9fa0.png)
![image](https://user-images.githubusercontent.com/103290917/162543181-41490532-c53a-4372-86fc-9cd1d7bc9d8c.png)

**Comment by BruunoSCP** [comment]
Here is what says when I write the name of a chart that it's not in the files btw, so the problem is not with the chart location in the folders. 
![image](https://user-images.githubusercontent.com/103290917/162543260-d705dfe3-0072-490d-bb8a-763ce71c25d9.png)
![image](https://user-images.githubusercontent.com/103290917/162543275-36a0d9ca-8420-42b3-b310-9f4aaa10e04f.png)

**Comment by accountrev** [comment]
Hello, please refer to the new Troubleshooting page to see if this help you!
https://github.com/accountrev/funkychart/wiki/Troubleshooting

**Comment by accountrev** [comment]
Rereading this post again. The Example charts were actually broken due to the updates I pushed out (they were made before release), so I removed them since they don't work anymore. Please refrain from using those lol.
But I'm still trying to figure out if the chart you're loading in this image is one of the example charts.

**Comment by Zelofa** [comment]
I still dont under though and i checked the trouble shooting and all the faq my lua and file is Zelofa.lua and Zelofa.mp3 but when i enter Zelofa.lua into the load song it gives me nothing and when i enter something im not loading any example chart i converted my 4K song with colors and username

**Comment by accountrev** [comment]
I pushed an update just now, you just need to select your executor when you load a chart. Tell me if this changes anything.

**Comment by accountrev** [comment]
https://github.com/accountrev/funkychart/releases/latest
